#!/usr/bin/env node
// tslint:disable-next-line:no-var-requires
const fs = require( 'fs' ).promises
// tslint:disable-next-line:no-var-requires
require( './lib/function.js' )
const args = process.argv.slice( 2, process.argv.length )

fs.readFile( './tsconfig-es.json' )
